### ISSUE TITLE
Criar objeto gun

### ISSUE THREAD

**Issue by GeovRodri** [leandrovianna/asteroides#6]
Esse objeto é responsável por disparar tiros (tiro é um objeto). Gun deve ter uma lista de Shot que são os tiros que vão estar na tela. A classe Gun deve ter um método disparar que vai criar um Shot, adiciona-lo a lista e esses shots que estão na lista devem ter nos seus steps um movimento continuo para cima (y--).

**Comment by leandrovianna** [comment]
Sistema de tiros da nave já criado. Só necessitando de melhorias.
